/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PeerRouteImport } from './routes/peer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as SessionSetupRouteImport } from './routes/session.setup'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as TeacherStudentIdRouteImport } from './routes/teacher.student.$id'
import { Route as SessionIdResultsRouteImport } from './routes/session.$id.results'

const PeerRoute = PeerRouteImport.update({
  id: '/peer',
  path: '/peer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSetupRoute = SessionSetupRouteImport.update({
  id: '/session/setup',
  path: '/session/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherStudentIdRoute = TeacherStudentIdRouteImport.update({
  id: '/teacher/student/$id',
  path: '/teacher/student/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdResultsRoute = SessionIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => SessionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/peer': typeof PeerRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/session/$id': typeof SessionIdRouteWithChildren
  '/session/setup': typeof SessionSetupRoute
  '/teacher/': typeof TeacherIndexRoute
  '/session/$id/results': typeof SessionIdResultsRoute
  '/teacher/student/$id': typeof TeacherStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/peer': typeof PeerRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/session/$id': typeof SessionIdRouteWithChildren
  '/session/setup': typeof SessionSetupRoute
  '/teacher': typeof TeacherIndexRoute
  '/session/$id/results': typeof SessionIdResultsRoute
  '/teacher/student/$id': typeof TeacherStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/peer': typeof PeerRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/session/$id': typeof SessionIdRouteWithChildren
  '/session/setup': typeof SessionSetupRoute
  '/teacher/': typeof TeacherIndexRoute
  '/session/$id/results': typeof SessionIdResultsRoute
  '/teacher/student/$id': typeof TeacherStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/peer'
    | '/auth/login'
    | '/auth/register'
    | '/session/$id'
    | '/session/setup'
    | '/teacher/'
    | '/session/$id/results'
    | '/teacher/student/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/peer'
    | '/auth/login'
    | '/auth/register'
    | '/session/$id'
    | '/session/setup'
    | '/teacher'
    | '/session/$id/results'
    | '/teacher/student/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/peer'
    | '/auth/login'
    | '/auth/register'
    | '/session/$id'
    | '/session/setup'
    | '/teacher/'
    | '/session/$id/results'
    | '/teacher/student/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PeerRoute: typeof PeerRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  SessionIdRoute: typeof SessionIdRouteWithChildren
  SessionSetupRoute: typeof SessionSetupRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherStudentIdRoute: typeof TeacherStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/peer': {
      id: '/peer'
      path: '/peer'
      fullPath: '/peer'
      preLoaderRoute: typeof PeerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/setup': {
      id: '/session/setup'
      path: '/session/setup'
      fullPath: '/session/setup'
      preLoaderRoute: typeof SessionSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/student/$id': {
      id: '/teacher/student/$id'
      path: '/teacher/student/$id'
      fullPath: '/teacher/student/$id'
      preLoaderRoute: typeof TeacherStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id/results': {
      id: '/session/$id/results'
      path: '/results'
      fullPath: '/session/$id/results'
      preLoaderRoute: typeof SessionIdResultsRouteImport
      parentRoute: typeof SessionIdRoute
    }
  }
}

interface SessionIdRouteChildren {
  SessionIdResultsRoute: typeof SessionIdResultsRoute
}

const SessionIdRouteChildren: SessionIdRouteChildren = {
  SessionIdResultsRoute: SessionIdResultsRoute,
}

const SessionIdRouteWithChildren = SessionIdRoute._addFileChildren(
  SessionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PeerRoute: PeerRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  SessionIdRoute: SessionIdRouteWithChildren,
  SessionSetupRoute: SessionSetupRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherStudentIdRoute: TeacherStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
